language: java

jdk:
  - oraclejdk8

os:
  - linux

dist: trusty

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew clean check
  - ./gradlew clean build javadoc jacocoTestReport
  - ./gradlew javadocJar sourcesJar

after_success:
  - bash <(curl -s https://codecov.io/bash)
