env:
  global:
    # GITHUB_SECRET_TOKEN
    - secure: "aQ0RW3VcYencsQ1+r4Etf2fIPrD83QgNStSGQV40R/zFTXK83c3m9S0WW0OgB41Cff0kAdPelmzwsrSL0MrBzZrl2T9OyMcRis+im1ET3za1w8+Qd7k3blrSLnx+D85LClFCQR06dkJkjXYva9VM8F/Al6sITiNHMrg8apsgcyJuA6xQhihl/j36LFDdVk9I8r2R5CVq5E7atX6+f6rruph0W7kkmX0S9VqwzV+/nJsKMisZPFd56zdoXDwLYuPwlzWrGfDpC11UztiO7l1gjTPTayCA6Pcx1lOXi4bhojwQV9KlGre7K1u7SpyGCssHi7e7HEnyk6izXiLEXscRwAvPCE044Y8Clo7VVDuvfwfEnPRJIIb0wdAwekVA6O4IUPwMqmmxDwZLlSpTbFOzKR68OLuUUYk/k5Yi5ldM3tHC1BFkE5g2ObmL9H8UgT3KpW7O4xeUplNyFgZAx9UlrUzWEZAxaw9MSZheF5oWfnBahVor7h0ZV75s4Vy/E+IsQrGOFuS1VaJeJgMFbhEsJaAyJ/ehWoUobdfF62pcE4PfVJwTHcg9srM12moy+Lo/sL6gS3MsdbYDkDoDEa0XSfHejKNf6W7ahPqIZqFcTi3i5mGVpwewiaopWXWCgdW+n3T0rhdkymn0PzNEXUFqLWwNS3L97sxwrsU7Hsl/fN8="
    # SONATYPE_USERNAME
    - secure: "NP+LLd69iGfBcTZu4AyUGzUQMIiG42Q6KQIxpW3rKa2nvfuJ9x506HFhOngq3XExquqeRcibTZlJYTEjadtt2ckb2wyZk8IbuwJNVkZj3xA2ExVyZF1lpEKqk1mwroPEjrmcUZA/zfgeBYrH2mk9NJ7txnodqCpC0lhSvupdMgoEFWvejAAaOsePLfpny6x8P8ItNZoIkZx19QNMHuepFAWJz+06MQ2gG2qJV7C1RkGeyLdV397yA4t4jJELMHERA7CsKsoI5W1tGMXPELRm6LEZ8Hon6N3menfZv1SR4ILyZkbLWf4d6D9fOeQwhMt9p6yKvwtxl0vi9cKutt/xWq+w0vpcKGK0SZCTWnvF9FzVuFwhr2UNvlOUI7+/I0G1eADTNHbWy3dUWOoqLMGRZbIA/7dQtf9Y88fd5fHPTUiLfHSVB8nJ/81jFDDT3NGWQ6beWUkLtPlJW5LU8X6fP3SofdwE4uPCBM5M1uEVcg6F3O2uaXEqeyhbzO2WtKA/4B279Se321R7hTYx7exWW4ZhAddWFxJP5A4bgmdI0uLZ0sjDlwh/ohBCrJoQfwVMGG4gSDlgYWbiHSNXxxEHlSV3mSAX9fA+h9U850itQHbn2EkEeXC4db7dKdV3C2IxP+Hsfv5XSFr1W6MpjlK/qFhtiw1dOx5esBCjfbuQB6U="
    # SONATYPE_PASSWORD
    - secure: "eGUSSm4kvQjUU8osN0TO/4pWk2ddoNAv7USo683VKzO2BcZ2E1hbWxz+MyObq13F6LiumDVhpgNAtj/ts6nIDz9plr9eabeP7SFDUyTeQu5CXuSbIHN2cvzRf0TC3f1T3D20kMXSv9g7xNLWUUgO0YQXahF+GUsoMxmzilyo0ZdP9Advr/VScqDp2eiPZ4zAIHDGPY5La4isFzbzkScj0wqPaXC0kUW2w854Dyh8A0N0XIAtEt+Q8fKCbuyry4dh+ZoPfDSiElM/Y8qIBYqOwZgOzliXPl2MO1Ywj7ucSpHY/+N6/OXiiQAkMEUC50vwIH1xAf5X10p1YkjVcmN2JYV1nNczNzx0GLWqE3k2RfW97GWVt3hDCWDXpEJ1mWuBns6WKC52iEBzJseS0izNx5kOpm8iXQQmhWKUIHQugw5hz6R0ncHchsXY3BtDI1t/YiJGjtaPnMrrCiuZrz+SnySOr6lwTzUUniHfeP6JOGdbzNA8lI+EzajMh6/tudQlNb3yT1SjFdaCqt3EyL3GAzhR7SARDyA+k6CnvWuunhb/mJWPEjGGWknImc1aW+eGOXQutO1jpl5HifJlJ5o5VtkalSOqcKNXPS+Y3SNPlMmOngZDWfFquxnvvnGyCG/kATtKYdDTG83dEV84IwLeSfg7qWu09IM0UoV6O2UKLJ0="
    # GPG_KEY_ID
    - secure: "F6KiplQD+pM9DNJ5V0U6+3jRQ/zQjN9Cf4O21jg87QCx8hEOQTgqGS0F4rweypOXwUYiTBUNbWjMM3Bc+sGrwRZOS05Sq0VnpFQ7Wx6+3QXCdsN9nw8iJtqio4llwhtAMuoFgHvsSlfgnLW33UKLnVpMmDMFsM8imhDf31Uv+nli9PXqaDcvNpk7z5MAJu0qmJQ7h5AcFzeTUvg2Ewt2H/cKB50dYsd+JW6ieCcFKKpi3phQgxFifNvBUH4M5ZCvTjYbJ2Bc/b3AjqeEtVBML7gxWQ37bAqslBk/StR21tTWTva8xthYUlEFC8Q/zaGaNrZHk32Lo/5GvvgjJjhzhvCiiXLQD3L1ocXde62ZeZk7ffYSkupqL/0reung9ww6sZQH/XfF/jKdkI/oeAuHeIGJgadzO2vRAvbDZFv3QaGd8dbAFcZv0yeTE348KZ7K7UivxkO2DVasIr2h1+HB7lGSWNXnrvarGFoXBUA6+kxMIwvNcwmU0M4gY9XDsbeVzAtagR1M7q5/l74RVU6UkX2EON1BbrvQog58qreV/dQ93R68/B97aboSszOFp8QIIdgckpC4W+Q3xNDv/0qL9Vjt63b9cGOcCTvAk7Oh+Xo3cvDjCM4pacisB68kwhwKSiY58yb0Thf+jN98vE4E6yVLdjIh9svS2Ma4LLwEKbE="
    # GPG_PASSPHRASE
    - secure: "pcJ0ttg84ILXVB6T4XKQUG9w12sn+inmoKB8nyfxz8myzbS6lGNtMQwSj7TEGmVZBg/11y/47JmWPKMtYw1eKF3iGSrNrPRC8xGiWME2FuvSsT46KsEww90SzQEKyExB8RAvKI9/NSTJ/cCRzeQCi3SVfGz4iILjjbE67QEhJMHAEM7Xvh77zS2Y81O7wn+ChY/ecMlwOPcnYz+9RJxQJRjMijOImlJMcOOducZiQYKvHi+1uMO8K3cDqZBvMeLRnbh1mx/IiL80NmCsKXtHa96UtVgWIuqgUFCAaGFV96KARYJDsLaoJFW2IpTrL/dJxHMLHvxvGNjoB5lH+1XO6+yOv9IFiSrxfeZc6VCZn72e2u0CurjrO25ybnvfADhEZv52mwdo64t/OzDttLVYRFQVdCOXhu3XV9uqoeU180/QjOD2zZNuKckC2LC76WOCqRBUfWSeoiy82E6zQb4tpmdgQwFABIqnKYMraaqCSuC/9U3FRQbdP4YkecoYZQPlOL6u4y+tFAL3taWhXmPVt4QFhEqDxTfrZl89V5/k/PWm60QOHMWW90vnffxFGthVWiV7AkbQF+q6MCR89mzylsQ+iUTKueAOZfxgqaEomxVSLTS1nbBlBw/CzEbi2qAol+nEaRX74d2jnhQ4JykDvbbD83LVEAAji7Whg6UYHUg="
    - GPG_KEY_LOCATION=".travis/sonatype_secret.gpg"
    - ENCRYPTED_GPG_KEY_LOCATION=".travis/sonatype_secret.gpg.enc"

language: java

jdk:
  - oraclejdk8

os:
  - linux

dist: trusty

branches:
  only:
    - master
    - dev

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod -R ug+x .travis
  - .travis/install.sh

script:
  - chmod -R ug+x .travis
  - .travis/build.sh
  - .travis/merge-dev-to-master-gate.sh
  - .travis/deploy-gate.sh
  - .travis/tag-master-gate.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
